version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: carbonable
      POSTGRES_USER: carbonable
      POSTGRES_DB: carbonable_ccpm
    ports:
    - 5432:5432
