version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: carbonable
      POSTGRES_USER: carbonable
      POSTGRES_DB: carbonable_ccpm
    ports:
    - 5432:5432
  redis:
    image: redis:7.2-alpine3.18
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
