# fly.toml app configuration file generated for carbonable-staging-ccrp-backend on 2023-06-28T10:23:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "carbonable-staging-ccrp-backend"
primary_region = "cdg"

# [deploy]
#   release_command = "npx prisma migrate deploy && npx prisma seed"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
