# fly.toml app configuration file generated for debug-ccrp-backend on 2024-08-21T17:09:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'debug-ccrp-backend'
primary_region = 'cdg'

[build]

[deploy]
####### release command , just in case you want to reset the db. -> "reset db && refactor db && push constants in db (ex: countries,sdg, first admin etc...)" 
release_command = 'npx prisma migrate deploy && npx prisma db seed'
[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
