import { Logger } from '@nestjs/common';
import {
  Args,
  ArgsType,
  Field,
  Int,
  Parent,
  Query,
  ResolveField,
  Resolver,
} from '@nestjs/graphql';
import { CarbonCredit } from '@prisma/client';
import { PrismaService } from '../../infrastructure/prisma.service';
import {
  GlobalDataService,
  ImpactMetricsService,
  ProjectFundingAllocationService,
  ProjectMetricsService,
  ProjectedDecarbonationService,
  CarbonAssetAllocationService,
} from '../services';
import { VisualizationViewType } from '../../schemas/graphql.autogenerated';

@ArgsType()
export class PaginationDTO {
  @Field(() => Int)
  page = 1;

  @Field(() => Int)
  count = 10;
}

export const CARBONABLE_COMPANY_ID = '01H5739RTVV0JV8M3DAN0C10ME';

@Resolver('CarbonCredit')
export class CarbonCreditResolver {
  private readonly logger = new Logger(CarbonCreditResolver.name);

  constructor(
    private prisma: PrismaService,
    private globalDataService: GlobalDataService,
    private projectedDecarbonation: ProjectedDecarbonationService,
    private projectFundingAllocation: ProjectFundingAllocationService,
    private projectMetrics: ProjectMetricsService,
    private impactMetrics: ImpactMetricsService,
    private carbonAssetAllocationService: CarbonAssetAllocationService,
  ) {}

  @ResolveField()
  async project(@Parent() carbonCredit: CarbonCredit) {
    const { id } = carbonCredit;
    return this.prisma.project.findUnique({ where: { id } });
  }

  @Query('getGlobalData')
  async getGlobalData(@Args('view') view: any) {
    return await this.globalDataService.get(view as VisualizationViewType);
  }

  @Query()
  async getProjectFundingAllocation(@Args('pagination') pagination: any) {
    return await this.projectFundingAllocation.get(
      (pagination as PaginationDTO) || new PaginationDTO(),
    );
  }

  @Query('getProjectMetrics')
  async getProjectMetrics(@Args('view') view: any) {
    return await this.projectMetrics.get(view as VisualizationViewType);
  }

  @Query('getImpactMetrics')
  async getImpactMetrics(@Args('view') view: any) {
    return await this.impactMetrics.get(view as VisualizationViewType);
  }

  @Query('companyCarbonAssetAllocation')
  async companyCarbonAssetAllocation(@Args('id') id: string) {
    return await this.carbonAssetAllocationService.getCompanyWide(id);
  }

  @Query('projectCarbonAssetAllocation')
  async projectCarbonAssetAllocation(@Args('id') id: string) {
    return await this.carbonAssetAllocationService.getProject(id);
  }

  @Query('businessUnitCarbonAssetAllocation')
  async businessUnitCarbonAssetAllocation(@Args('id') id: string) {
    return await this.carbonAssetAllocationService.getBusinessUnit(id);
  }
}
