name: integration
on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    services:
      redis:
        image: redis:7.2-alpine3.18
        ports:
          - 6379:6379
      pg:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: carbonable_ccpm_test
        ports:
          - 5432:5432

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Init db
        run: pnpm run test:db:reset

      - name: Run tests
        run: pnpm run test:integration
